<?php
defined('BASEPATH') or exit('No direct script access allowed');

/** Standalone, organization-scoped Lead Discovery API. Google Places is only called when configured. */
class Api_lead_discovery extends Api_controller
{
    private array $user; private string $org;
    private function guard(): bool { $u=$this->requirePermission('system.authenticated'); if (!$u) return false; $this->user=$u; $this->org='user:' . (int)$u['id']; return true; }
    private function id(): string { return bin2hex(random_bytes(16)); }
    private function now(): string { return gmdate('c'); }
    private function activity(?string $lead, string $type, array $detail=[]): void { $this->db->insert('lead_activities',['id'=>$this->id(),'lead_id'=>$lead,'organization_id'=>$this->org,'actor_id'=>$this->user['id'],'type'=>$type,'detail'=>json_encode($detail),'created_at'=>$this->now()]); }
    private function lead(string $id): ?array { return $this->db->get_where('leads',['id'=>$id,'organization_id'=>$this->org],1)->row_array() ?: null; }
    private function safeCsv(string $v): string { return preg_match('/^[=+\-@]/', $v) ? "'".$v : $v; }

    public function search() {
        if(!$this->guard())return; $b=$this->jsonBody(); $q=trim((string)($b['query']??''));
        if(strlen($q)<3 || strlen($q)>300)return $this->jsonError('query must be 3–300 characters');
        if(($b['provider']??'google_places')!=='google_places')return $this->jsonError('provider is not implemented',422);
        $started=microtime(true); $key=getenv('GOOGLE_PLACES_API_KEY'); $raw=[]; $error=null;
        if(!$key) $error='Google Places is disabled: configure GOOGLE_PLACES_API_KEY. No synthetic results were created.';
        else { $ctx=stream_context_create(['http'=>['method'=>'POST','timeout'=>12,'header'=>"Content-Type: application/json\r\nX-Goog-Api-Key: {$key}\r\nX-Goog-FieldMask: places.id,places.displayName,places.formattedAddress,places.types,places.nationalPhoneNumber,places.websiteUri,places.location\r\n",'content'=>json_encode(['textQuery'=>$q,'maxResultCount'=>min(20,max(1,(int)($b['limit']??20)))])]]); $json=@file_get_contents('https://places.googleapis.com/v1/places:searchText',false,$ctx); $parsed=$json?json_decode($json,true):null; if(!$parsed || isset($parsed['error'])) $error=$parsed['error']['message']??'Google Places request failed or timed out'; else $raw=$parsed['places']??[]; }
        $new=0;$dupes=0;$results=[];
        foreach($raw as $p){ $sid=(string)($p['id']??''); if(!$sid)continue; $existing=$this->db->get_where('leads',['organization_id'=>$this->org,'source'=>'google_places','source_id'=>$sid],1)->row_array(); $name=(string)($p['displayName']['text']??'Unnamed business'); $types=$p['types']??[]; $record=['organization_id'=>$this->org,'source'=>'google_places','source_id'=>$sid,'name'=>$name,'category'=>implode(', ',array_slice($types,0,3))?:null,'address'=>$p['formattedAddress']??null,'phone'=>$p['nationalPhoneNumber']??null,'website'=>$p['websiteUri']??null,'latitude'=>$p['location']['latitude']??null,'longitude'=>$p['location']['longitude']??null,'metadata'=>json_encode(['provider'=>'Google Places','types'=>$types]),'updated_at'=>$this->now()];
          if($existing){$this->db->where('id',$existing['id'])->where('organization_id',$this->org)->update('leads',$record);$record['id']=$existing['id'];$dupes++;$this->activity($existing['id'],'DUPLICATE_DETECTED',['rule'=>'provider_source_id']);} else {$record+=['id'=>$this->id(),'status'=>'new','owner_id'=>null,'created_at'=>$this->now()];$this->db->insert('leads',$record);$new++;$this->activity($record['id'],'LEAD_DISCOVERED',['query'=>$q,'provider'=>'google_places']);} $results[]=$record;
        }
        $this->db->insert('search_history',['id'=>$this->id(),'organization_id'=>$this->org,'user_id'=>$this->user['id'],'query'=>$q,'provider'=>'google_places','filters'=>json_encode(['limit'=>$b['limit']??20]),'results_returned'=>count($raw),'new_leads_created'=>$new,'duplicates_detected'=>$dupes,'errors'=>$error,'duration_ms'=>(int)((microtime(true)-$started)*1000),'created_at'=>$this->now()]);
        if($error)return $this->jsonError($error,503,['providerStatus'=>'DISABLED']); $this->json(['provider'=>'google_places','providerStatus'=>'IMPLEMENTED','results'=>$results,'newLeadsCreated'=>$new,'duplicatesDetected'=>$dupes]);
    }
    public function leads($id=null){if(!$this->guard())return;if($id){$x=$this->lead($id);return $x?$this->json($x):$this->jsonError('lead not found',404);} $this->db->where('organization_id',$this->org);if($s=$this->input->get('status'))$this->db->where('status',$s);$this->json(['leads'=>$this->db->order_by('updated_at','DESC')->limit(250)->get('leads')->result_array()]);}
    public function collections($id=null){if(!$this->guard())return;$method=$this->input->method(true);if($id&&$method==='PATCH'){$b=$this->jsonBody();$name=trim((string)($b['name']??''));if(!$name)return $this->jsonError('name required');$this->db->where(['id'=>$id,'organization_id'=>$this->org])->update('collections',['name'=>$name,'updated_at'=>$this->now()]);return $this->json(['ok'=>true]);}if($id&&$method==='DELETE'){$this->db->where('collection_id',$id)->delete('collection_leads');$this->db->where(['id'=>$id,'organization_id'=>$this->org])->delete('collections');return $this->json(['ok'=>true]);}if($method==='POST'){$name=trim((string)($this->jsonBody()['name']??''));if(!$name)return $this->jsonError('name required');$x=['id'=>$this->id(),'organization_id'=>$this->org,'name'=>$name,'created_at'=>$this->now(),'updated_at'=>$this->now()];$this->db->insert('collections',$x);return $this->json($x,201);}$this->json(['collections'=>$this->db->where('organization_id',$this->org)->order_by('name')->get('collections')->result_array()]);}
    public function collection_leads($collection,$lead=null){if(!$this->guard())return;if(!$this->db->get_where('collections',['id'=>$collection,'organization_id'=>$this->org],1)->row_array())return $this->jsonError('collection not found',404);if($lead){if(!$this->lead($lead))return $this->jsonError('lead not found',404);if($this->input->method(true)==='DELETE'){$this->db->where(['collection_id'=>$collection,'lead_id'=>$lead])->delete('collection_leads');$this->activity($lead,'LEAD_REMOVED_FROM_COLLECTION',['collectionId'=>$collection]);}else{$this->db->replace('collection_leads',['collection_id'=>$collection,'lead_id'=>$lead]);$this->activity($lead,'LEAD_ADDED_TO_COLLECTION',['collectionId'=>$collection]);}return $this->json(['ok'=>true]);}$this->json(['leads'=>$this->db->select('l.*')->from('leads l')->join('collection_leads cl','cl.lead_id=l.id')->where(['cl.collection_id'=>$collection,'l.organization_id'=>$this->org])->get()->result_array()]);}
    public function status($id){if(!$this->guard())return;$x=$this->lead($id);$v=$this->jsonBody()['status']??'';if(!$x)return $this->jsonError('lead not found',404);if(!in_array($v,['new','contacted','qualified','disqualified','converted'],true))return $this->jsonError('invalid status');$this->db->where('id',$id)->update('leads',['status'=>$v,'updated_at'=>$this->now()]);$this->activity($id,'STATUS_CHANGED',['from'=>$x['status'],'to'=>$v]);$this->json(['ok'=>true]);}
    public function owner($id){if(!$this->guard())return;if(!$this->lead($id))return $this->jsonError('lead not found',404);$owner=$this->jsonBody()['ownerId']??null;if($owner!==null&&!ctype_digit((string)$owner))return $this->jsonError('ownerId must be an integer or null');$this->db->where('id',$id)->update('leads',['owner_id'=>$owner,'updated_at'=>$this->now()]);$this->activity($id,$owner===null?'OWNER_REMOVED':'OWNER_ASSIGNED',['ownerId'=>$owner]);$this->json(['ok'=>true]);}
    public function notes($id){if(!$this->guard())return;if(!$this->lead($id))return $this->jsonError('lead not found',404);if($this->input->method(true)==='POST'){$body=trim((string)($this->jsonBody()['body']??''));if(!$body||strlen($body)>4000)return $this->jsonError('note must be 1–4000 characters');$n=['id'=>$this->id(),'lead_id'=>$id,'organization_id'=>$this->org,'author_id'=>$this->user['id'],'body'=>$body,'created_at'=>$this->now()];$this->db->insert('lead_notes',$n);$this->activity($id,'NOTE_ADDED',[]);return $this->json($n,201);}$this->json(['notes'=>$this->db->where(['lead_id'=>$id,'organization_id'=>$this->org])->order_by('created_at','DESC')->get('lead_notes')->result_array()]);}
    public function duplicates($resolve=false){if(!$this->guard())return;if($resolve){$b=$this->jsonBody();$id=(string)($b['candidateId']??'');$action=(string)($b['action']??'');if(!in_array($action,['keep_a','keep_b','merge','ignore'],true))return $this->jsonError('invalid duplicate resolution');$c=$this->db->get_where('duplicate_candidates',['id'=>$id,'organization_id'=>$this->org],1)->row_array();if(!$c)return $this->jsonError('duplicate candidate not found',404);$this->db->where('id',$id)->update('duplicate_candidates',['status'=>'resolved']);$this->db->insert('duplicate_resolutions',['id'=>$this->id(),'candidate_id'=>$id,'organization_id'=>$this->org,'resolver_id'=>$this->user['id'],'action'=>$action,'created_at'=>$this->now()]);$this->activity($c['lead_a_id'],'DUPLICATE_RESOLVED',['candidateId'=>$id,'action'=>$action]);return $this->json(['ok'=>true]);}$this->json(['duplicates'=>$this->db->where(['organization_id'=>$this->org,'status'=>'open'])->order_by('created_at','DESC')->get('duplicate_candidates')->result_array()]);}
    public function coverage(){if(!$this->guard())return;$all=$this->db->where('organization_id',$this->org)->get('leads')->result_array();$n=count($all);$fields=['name'=>'Business Name','address'=>'Address','category'=>'Category','phone'=>'Phone','website'=>'Website'];$out=[];foreach($fields as $f=>$label){$filled=count(array_filter($all,fn($x)=>!empty($x[$f])));$out[]=['field'=>$label,'coverage'=>$n?round(100*$filled/$n,1):0,'missing'=>$n-$filled];}$this->json(['leadCount'=>$n,'fields'=>$out]);}
    public function history(){if(!$this->guard())return;$this->json(['history'=>$this->db->where('organization_id',$this->org)->order_by('created_at','DESC')->limit(100)->get('search_history')->result_array()]);}
    public function summary(){if(!$this->guard())return;$rows=$this->db->select('status, COUNT(*) total')->where('organization_id',$this->org)->group_by('status')->get('leads')->result_array();$this->json(['pipeline'=>$rows]);}
    public function export($mode='json'){if(!$this->guard())return;$b=$this->jsonBody();$this->db->where('organization_id',$this->org);if(!empty($b['status']))$this->db->where('status',$b['status']);$leads=$this->db->get('leads')->result_array();$format=$mode==='csv'?'csv':($b['format']??'json');$this->db->insert('export_history',['id'=>$this->id(),'organization_id'=>$this->org,'user_id'=>$this->user['id'],'format'=>$format,'filters'=>json_encode($b),'lead_count'=>count($leads),'created_at'=>$this->now()]);foreach($leads as $x)$this->activity($x['id'],'LEAD_EXPORTED',['format'=>$format]);if($format==='csv'){$keys=['name','category','address','city','country','phone','website','status'];$lines=[implode(',',$keys)];foreach($leads as $l){$lines[]=implode(',',array_map(fn($k)=>'"'.str_replace('"','""',$this->safeCsv((string)($l[$k]??''))).'"',$keys));}$this->output->set_content_type('text/csv')->set_header('Content-Disposition: attachment; filename="leads.csv"')->set_output(implode("\r\n",$lines));return;}$this->json(['leads'=>$leads,'count'=>count($leads)]);}
}
