import path from 'node:path';
import { loadNodeRuntime, useHostFilesystem } from '@php-wasm/node';
import { PHP, ProcessIdAllocator } from '@php-wasm/universal';
const APP_ROOT = '/home/user/AI-WORKFORCE';
process.env.AI_WORKFORCE_DB_DRIVER='pdo_sqlite'; process.env.VP_DB_DRIVER='pdo_sqlite';
const allocator = new ProcessIdAllocator();
const runtime = await loadNodeRuntime('8.2', { emscriptenOptions: { processId: allocator.claim() } });
const php = new PHP(runtime); useHostFilesystem(php);
const code = `<?php
chdir('${APP_ROOT}');
putenv('AI_WORKFORCE_DB_DRIVER=pdo_sqlite'); putenv('VP_DB_DRIVER=pdo_sqlite');
putenv('AI_WORKFORCE_SQLITE_PATH=${APP_ROOT}/application/data/ai_workforce-test.sqlite');
putenv('AI_WORKFORCE_SKIP_ENV_FILE=1'); putenv('AI_WORKFORCE_DISABLE_REAL_PROVIDERS=1');
ini_set('display_errors','1'); error_reporting(E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_WARNING);
define('STDIN', fopen('php://stdin','r'));
$_SERVER['argv']=['index.php','tools','sports-providers']; $_SERVER['argc']=3;
define('AI_WORKFORCE_NO_EXIT', true);
require '${APP_ROOT}/index.php';
`;
const r = await php.run({ code });
console.log(new TextDecoder().decode(r.bytes));
