import type { FastifyInstance, FastifyRequest } from "fastify";
import { ExportRequestSchema, ResolveDuplicateSchema } from "../../../../packages/shared/src/leadDiscovery.js";
import { requireLeadAccess, type LeadPrincipal } from "../auth.js";
import { mapLeadRow } from "../leadRepository.js";
const leadColumns="id, organization_id, source, source_id, name, category, address, city, region, country, phone, website, latitude, longitude, status, owner_id, metadata, created_at, updated_at";
const writable=async (request: FastifyRequest):Promise<LeadPrincipal>=>{const user=await requireLeadAccess(request);if(!user.permissions.includes("lead.write"))throw Object.assign(new Error("forbidden"),{statusCode:403});return user;};
const audit=(app:FastifyInstance,user:LeadPrincipal,leadId:string,type:string,detail:Record<string,unknown>)=>app.db.query("INSERT INTO lead_activities (organization_id,lead_id,actor_id,type,detail) VALUES ($1,$2,$3,$4,$5::jsonb)",[user.organizationId,leadId,user.sub,type,JSON.stringify(detail)]);
const csv=(value:unknown)=>{const text=String(value??"");const safe=/^[=+\-@]/.test(text)?`'${text}`:text;return `"${safe.replaceAll('"','""')}"`};
export async function intelligenceRoutes(app:FastifyInstance):Promise<void>{
  app.get("/history",async request=>{const user=await requireLeadAccess(request);const rows=await app.db.query("SELECT id,query,provider,filters,results_returned,new_leads_created,duplicates_detected,errors,duration_ms,created_at FROM search_history WHERE organization_id=$1 ORDER BY created_at DESC LIMIT 100",[user.organizationId]);return {history:rows.rows.map(x=>({id:x.id,query:x.query,provider:x.provider,filters:x.filters,resultsReturned:x.results_returned,newLeadsCreated:x.new_leads_created,duplicatesDetected:x.duplicates_detected,errors:x.errors,durationMs:x.duration_ms,createdAt:x.created_at}))};});
  app.get("/duplicates",async request=>{const user=await requireLeadAccess(request);const rows=await app.db.query("SELECT d.*,a.name AS lead_a_name,b.name AS lead_b_name FROM duplicate_candidates d JOIN leads a ON a.id=d.lead_a_id JOIN leads b ON b.id=d.lead_b_id WHERE d.organization_id=$1 AND d.status='open' ORDER BY d.created_at DESC",[user.organizationId]);return {duplicates:rows.rows.map(x=>({id:x.id,leadAId:x.lead_a_id,leadBId:x.lead_b_id,leadAName:x.lead_a_name,leadBName:x.lead_b_name,ruleName:x.rule_name,confidence:Number(x.confidence),status:x.status,createdAt:x.created_at}))};});
  app.post("/duplicates/resolve",async request=>{const user=await writable(request);const body=ResolveDuplicateSchema.parse(request.body);const candidate=await app.db.query("SELECT * FROM duplicate_candidates WHERE id=$1 AND organization_id=$2 AND status='open'",[body.candidateId,user.organizationId]);const c=candidate.rows[0];if(!c)throw Object.assign(new Error("duplicate candidate not found"),{statusCode:404});const a=String(c.lead_a_id),b=String(c.lead_b_id);if(body.action==="merge"){await app.db.query("UPDATE leads a SET category=COALESCE(a.category,b.category),address=COALESCE(a.address,b.address),city=COALESCE(a.city,b.city),region=COALESCE(a.region,b.region),country=COALESCE(a.country,b.country),phone=COALESCE(a.phone,b.phone),website=COALESCE(a.website,b.website),latitude=COALESCE(a.latitude,b.latitude),longitude=COALESCE(a.longitude,b.longitude),updated_at=now() FROM leads b WHERE a.id=$1 AND b.id=$2 AND a.organization_id=$3 AND b.organization_id=$3",[a,b,user.organizationId]);await app.db.query("UPDATE leads SET status='disqualified',metadata=metadata || jsonb_build_object('duplicateResolution',jsonb_build_object('keptLeadId',$1,'reason','merged')),updated_at=now() WHERE id=$2 AND organization_id=$3",[a,b,user.organizationId]);await audit(app,user,a,"DUPLICATE_RESOLVED",{candidateId:body.candidateId,action:"merge",mergedLeadId:b});}else if(body.action!=="ignore"){const keep=body.action==="keep_a"?a:b,discard=body.action==="keep_a"?b:a;await app.db.query("UPDATE leads SET status='disqualified',metadata=metadata || jsonb_build_object('duplicateResolution',jsonb_build_object('keptLeadId',$1,'reason','discarded')),updated_at=now() WHERE id=$2 AND organization_id=$3",[keep,discard,user.organizationId]);await audit(app,user,keep,"DUPLICATE_RESOLVED",{candidateId:body.candidateId,action:body.action,discardedLeadId:discard});}else await audit(app,user,a,"DUPLICATE_RESOLVED",{candidateId:body.candidateId,action:"ignore"});await app.db.query("UPDATE duplicate_candidates SET status='resolved' WHERE id=$1 AND organization_id=$2",[body.candidateId,user.organizationId]);await app.db.query("INSERT INTO duplicate_resolutions (candidate_id,organization_id,resolver_id,action) VALUES ($1,$2,$3,$4)",[body.candidateId,user.organizationId,user.sub,body.action]);return {ok:true};});
  const exportLeads=async (user:LeadPrincipal,raw:unknown)=>{const filters=ExportRequestSchema.parse(raw);const where=["l.organization_id=$1"];const values:unknown[]=[user.organizationId];const add=(sql:string,value:unknown)=>{values.push(value);where.push(`${sql}=$${values.length}`)};if(filters.status)add("l.status",filters.status);if(filters.ownerId)add("l.owner_id",filters.ownerId);if(filters.country)add("l.country",filters.country);if(filters.category)add("l.category",filters.category);if(filters.from){values.push(filters.from);where.push(`l.created_at >= $${values.length}`)}if(filters.to){values.push(filters.to);where.push(`l.created_at <= $${values.length}`)}let join="";if(filters.collectionId){values.push(filters.collectionId);join=` JOIN collection_leads cl ON cl.lead_id=l.id AND cl.collection_id=$${values.length}`;}const rows=await app.db.query(`SELECT ${leadColumns} FROM leads l ${join} WHERE ${where.join(" AND ")} ORDER BY l.created_at DESC`,values);return {filters,leads:rows.rows.map(mapLeadRow)};};
  app.post("/export/preview",async request=>{const user=await requireLeadAccess(request);const {leads}=await exportLeads(user,request.body);return {rows:leads.slice(0,25).map(lead=>Object.fromEntries(Object.entries(lead).map(([k,v])=>[k,typeof v==="string"&&/^[=+\-@]/.test(v)?`'${v}`:v]))),count:leads.length,csvSafe:true};});
  app.post("/export",async request=>{const user=await writable(request);const {filters,leads}=await exportLeads(user,request.body);await app.db.query("INSERT INTO export_history (organization_id,user_id,format,filters,lead_count) VALUES ($1,$2,'json',$3::jsonb,$4)",[user.organizationId,user.sub,JSON.stringify(filters),leads.length]);await Promise.all(leads.map(lead=>audit(app,user,lead.id,"LEAD_EXPORTED",{format:"json"})));return {leads,count:leads.length};});
  app.post("/export/csv",async (request,reply)=>{const user=await writable(request);const {filters,leads}=await exportLeads(user,request.body);const keys=["name","category","address","city","country","phone","website","status"] as const;const body=[keys.join(","),...leads.map(lead=>keys.map(key=>csv(lead[key])).join(","))].join("\r\n");await app.db.query("INSERT INTO export_history (organization_id,user_id,format,filters,lead_count) VALUES ($1,$2,'csv',$3::jsonb,$4)",[user.organizationId,user.sub,JSON.stringify(filters),leads.length]);await Promise.all(leads.map(lead=>audit(app,user,lead.id,"LEAD_EXPORTED",{format:"csv"})));return reply.header("content-type","text/csv; charset=utf-8").header("content-disposition","attachment; filename=leads.csv").send(body);});
}
