import type { FastifyInstance, FastifyRequest } from "fastify";
import { AddCollectionLeadsSchema, AddLeadNoteSchema, ChangeLeadOwnerSchema, ChangeLeadStatusSchema, CreateCollectionSchema } from "../../../../packages/shared/src/leadDiscovery.js";
import { requireLeadAccess, type LeadPrincipal } from "../auth.js";
import { mapLeadRow } from "../leadRepository.js";
const UUID = /^[0-9a-f]{8}-[0-9a-f-]{27,}$/i;
const id = (request: FastifyRequest, key: string) => { const value = (request.params as Record<string,string>)[key]; if (!UUID.test(value ?? "")) throw Object.assign(new Error(`invalid ${key}`), { statusCode: 400 }); return value!; };
const writable = async (request: FastifyRequest): Promise<LeadPrincipal> => { const user=await requireLeadAccess(request);if(!user.permissions.includes("lead.write"))throw Object.assign(new Error("forbidden"),{statusCode:403});return user; };
const activity = async (app: FastifyInstance, principal: LeadPrincipal, leadId: string | null, type: string, detail: Record<string,unknown> = {}) => app.db.query("INSERT INTO lead_activities (organization_id,lead_id,actor_id,type,detail) VALUES ($1,$2,$3,$4,$5::jsonb)",[principal.organizationId,leadId,principal.sub,type,JSON.stringify(detail)]);
const leadColumns="id, organization_id, source, source_id, name, category, address, city, region, country, phone, website, latitude, longitude, status, owner_id, metadata, created_at, updated_at";

export async function pipelineRoutes(app: FastifyInstance): Promise<void> {
  app.get("/summary", async request => { const user=await requireLeadAccess(request);const result=await app.db.query("SELECT status, COUNT(*)::int AS total FROM leads WHERE organization_id=$1 GROUP BY status",[user.organizationId]);return { pipeline: result.rows.map(row=>({status:row.status,total:Number(row.total)}))}; });
  app.get("/pipeline", async request => { const user=await requireLeadAccess(request);const statuses=["new","contacted","qualified","disqualified","converted"] as const;const columns=Object.fromEntries(statuses.map(status=>[status,[] as unknown[]]));const result=await app.db.query(`SELECT ${leadColumns} FROM leads WHERE organization_id=$1 ORDER BY updated_at DESC`,[user.organizationId]);for(const row of result.rows)columns[row.status as keyof typeof columns]?.push(mapLeadRow(row));return {statuses,columns}; });
  app.patch("/leads/:id/status", async request => { const user=await writable(request);const leadId=id(request,"id");const body=ChangeLeadStatusSchema.parse(request.body);const changed=await app.db.query("UPDATE leads SET status=$1,updated_at=now() WHERE id=$2 AND organization_id=$3 RETURNING status",[body.status,leadId,user.organizationId]);if(!changed.rows[0])throw Object.assign(new Error("lead not found"),{statusCode:404});await activity(app,user,leadId,"STATUS_CHANGED",{to:body.status});return {ok:true}; });
  app.patch("/leads/:id/owner", async request => { const user=await writable(request);const leadId=id(request,"id");const body=ChangeLeadOwnerSchema.parse(request.body);const changed=await app.db.query("UPDATE leads SET owner_id=$1,updated_at=now() WHERE id=$2 AND organization_id=$3 RETURNING id",[body.ownerId,leadId,user.organizationId]);if(!changed.rows[0])throw Object.assign(new Error("lead not found"),{statusCode:404});await activity(app,user,leadId,body.ownerId?"OWNER_ASSIGNED":"OWNER_REMOVED",{ownerId:body.ownerId});return {ok:true}; });
  app.get("/leads/:id/notes", async request => {const user=await requireLeadAccess(request);const leadId=id(request,"id");const notes=await app.db.query("SELECT id,lead_id,author_id,body,created_at FROM lead_notes WHERE organization_id=$1 AND lead_id=$2 ORDER BY created_at DESC",[user.organizationId,leadId]);return {notes:notes.rows.map(n=>({id:n.id,leadId:n.lead_id,authorId:n.author_id,body:n.body,createdAt:n.created_at}))};});
  app.post("/leads/:id/notes", async request => {const user=await writable(request);const leadId=id(request,"id");const body=AddLeadNoteSchema.parse(request.body);const note=await app.db.query("INSERT INTO lead_notes (organization_id,lead_id,author_id,body) SELECT $1,$2,$3,$4 WHERE EXISTS (SELECT 1 FROM leads WHERE id=$2 AND organization_id=$1) RETURNING id,lead_id,author_id,body,created_at",[user.organizationId,leadId,user.sub,body.body]);if(!note.rows[0])throw Object.assign(new Error("lead not found"),{statusCode:404});await activity(app,user,leadId,"NOTE_ADDED");return {id:note.rows[0].id,leadId,authorId:user.sub,body:note.rows[0].body,createdAt:note.rows[0].created_at};});
  app.get("/leads/:id/activity", async request => {const user=await requireLeadAccess(request);const leadId=id(request,"id");const result=await app.db.query("SELECT id,lead_id,actor_id,type,detail,created_at FROM lead_activities WHERE organization_id=$1 AND lead_id=$2 ORDER BY created_at DESC",[user.organizationId,leadId]);return {activity:result.rows.map(x=>({id:x.id,leadId:x.lead_id,actorId:x.actor_id,type:x.type,detail:x.detail,createdAt:x.created_at}))};});
  app.get("/collections", async request => {const user=await requireLeadAccess(request);const result=await app.db.query("SELECT c.id,c.organization_id,c.name,c.created_at,c.updated_at,COUNT(cl.lead_id)::int AS lead_count FROM collections c LEFT JOIN collection_leads cl ON cl.collection_id=c.id WHERE c.organization_id=$1 GROUP BY c.id ORDER BY c.name",[user.organizationId]);return {collections:result.rows.map(x=>({id:x.id,organizationId:x.organization_id,name:x.name,leadCount:Number(x.lead_count),createdAt:x.created_at,updatedAt:x.updated_at}))};});
  app.post("/collections", async request => {const user=await writable(request);const body=CreateCollectionSchema.parse(request.body);const result=await app.db.query("INSERT INTO collections (organization_id,name) VALUES ($1,$2) RETURNING id,organization_id,name,created_at,updated_at",[user.organizationId,body.name]);const x=result.rows[0]!;return {id:x.id,organizationId:x.organization_id,name:x.name,leadCount:0,createdAt:x.created_at,updatedAt:x.updated_at};});
  app.patch("/collections/:id", async request => {const user=await writable(request);const collectionId=id(request,"id");const body=CreateCollectionSchema.parse(request.body);const result=await app.db.query("UPDATE collections SET name=$1,updated_at=now() WHERE id=$2 AND organization_id=$3 RETURNING id",[body.name,collectionId,user.organizationId]);if(!result.rows[0])throw Object.assign(new Error("collection not found"),{statusCode:404});return {ok:true};});
  app.delete("/collections/:id", async request => {const user=await writable(request);const collectionId=id(request,"id");const result=await app.db.query("DELETE FROM collections WHERE id=$1 AND organization_id=$2 RETURNING id",[collectionId,user.organizationId]);if(!result.rows[0])throw Object.assign(new Error("collection not found"),{statusCode:404});return {ok:true};});
  app.get("/collections/:id/leads", async request => {const user=await requireLeadAccess(request);const collectionId=id(request,"id");const result=await app.db.query(`SELECT ${leadColumns} FROM leads l JOIN collection_leads cl ON cl.lead_id=l.id JOIN collections c ON c.id=cl.collection_id WHERE c.id=$1 AND c.organization_id=$2 ORDER BY l.updated_at DESC`,[collectionId,user.organizationId]);return {leads:result.rows.map(mapLeadRow)};});
  app.post("/collections/:id/leads", async request => {const user=await writable(request);const collectionId=id(request,"id");const body=AddCollectionLeadsSchema.parse(request.body);const collection=await app.db.query("SELECT id FROM collections WHERE id=$1 AND organization_id=$2",[collectionId,user.organizationId]);if(!collection.rows[0])throw Object.assign(new Error("collection not found"),{statusCode:404});let added=0;for(const leadId of body.leadIds){const r=await app.db.query("INSERT INTO collection_leads (collection_id,lead_id) SELECT $1,$2 WHERE EXISTS (SELECT 1 FROM leads WHERE id=$2 AND organization_id=$3) ON CONFLICT DO NOTHING RETURNING lead_id",[collectionId,leadId,user.organizationId]);if(r.rows[0]){added++;await activity(app,user,leadId,"LEAD_ADDED_TO_COLLECTION",{collectionId});}}return {ok:true,added};});
  app.delete("/collections/:id/leads/:leadId", async request => {const user=await writable(request);const collectionId=id(request,"id");const leadId=id(request,"leadId");const deleted=await app.db.query("DELETE FROM collection_leads cl USING collections c, leads l WHERE cl.collection_id=c.id AND cl.lead_id=l.id AND c.id=$1 AND c.organization_id=$2 AND l.id=$3 AND l.organization_id=$2 RETURNING cl.lead_id",[collectionId,user.organizationId,leadId]);if(deleted.rows[0])await activity(app,user,leadId,"LEAD_REMOVED_FROM_COLLECTION",{collectionId});return {ok:true,removed:deleted.rows.length};});
}
