"use client";
import { useEffect, useMemo, useState } from "react";
import type { Lead, LeadStatus } from "../../../../../packages/shared/src/leadDiscovery";
import { leadApi, leadDiscoveryApi, leadPipelineApi } from "../../lib/leadDiscovery";
import { Navigation } from "../layout/Navigation";
const statuses: LeadStatus[] = ["new", "contacted", "qualified", "disqualified", "converted"];
export function LeadWorkspace({ mode }: { mode: "discovery" | "pipeline" }) {
  const [token, setToken] = useState(""); const [query, setQuery] = useState("Restaurants in Lagos"); const [leads, setLeads] = useState<Lead[]>([]); const [columns, setColumns] = useState<Record<LeadStatus, Lead[]> | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => setToken(localStorage.getItem("lead-api-token") ?? ""), []);
  const saveToken = (value: string) => { setToken(value); localStorage.setItem("lead-api-token", value); };
  const load = async () => { if (!token) return; setBusy(true); setError(""); try { if (mode === "pipeline") { const result = await leadPipelineApi.pipeline(token); setColumns(result.columns); } else { const result = await leadApi.list(token); setLeads(result.leads); } } catch (e) { setError(e instanceof Error ? e.message : "Unable to load leads"); } finally { setBusy(false); } };
  useEffect(() => { void load(); }, [token, mode]);
  const search = async (event: React.FormEvent) => { event.preventDefault(); if (!token) return setError("Add a valid API JWT before searching."); setBusy(true); setError(""); try { await leadDiscoveryApi.search({ query, provider: "google_places", limit: 20 }, token); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Search failed"); } finally { setBusy(false); } };
  const move = async (lead: Lead, status: LeadStatus) => { try { await leadApi.updateStatus(lead.id, status, token); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Status update failed"); } };
  const count = useMemo(() => mode === "pipeline" ? Object.values(columns ?? {}).reduce((sum, items) => sum + items.length, 0) : leads.length, [mode, columns, leads]);
  return <><Navigation /><main className="mx-auto max-w-7xl px-6 py-10"><header className="mb-8 flex items-end justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.2em] text-cyan-400">Scout / Sales intelligence</p><h1 className="mt-2 text-3xl font-bold text-white">{mode === "pipeline" ? "Lead pipeline" : "Lead discovery"}</h1><p className="mt-2 text-slate-400">Live API workspace. Provider data is never simulated.</p></div><span className="rounded-full border border-slate-700 bg-slate-900 px-3 py-1 text-sm text-slate-300">{count} leads</span></header><section className="mb-6 rounded-xl border border-slate-800 bg-slate-900 p-4"><label className="block text-xs font-medium uppercase tracking-wide text-slate-400">Fastify API JWT</label><input value={token} onChange={e => saveToken(e.target.value)} placeholder="Paste a JWT with lead.read / lead.write permissions" className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white outline-none focus:border-cyan-400" /></section>{mode === "discovery" && <form onSubmit={search} className="mb-6 flex gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4"><input value={query} onChange={e => setQuery(e.target.value)} className="min-w-0 flex-1 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white" aria-label="Business query"/><button disabled={busy} className="rounded-lg bg-cyan-400 px-4 py-2 font-semibold text-slate-950 disabled:opacity-50">{busy ? "Working…" : "Search Google Places"}</button></form>}{error && <p role="alert" className="mb-5 rounded-lg border border-red-900 bg-red-950/40 p-3 text-red-200">{error}</p>}{mode === "discovery" ? <LeadTable leads={leads} onMove={move} disabled={busy}/> : <Pipeline columns={columns} onMove={move} disabled={busy}/>}</main></>;
}
function LeadTable({ leads, onMove, disabled }: { leads: Lead[]; onMove: (lead: Lead, status: LeadStatus) => void; disabled: boolean }) { return <section className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-900"><table className="w-full text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase tracking-wide text-slate-400"><tr><th className="p-4">Business</th><th>Category</th><th>Contact</th><th>Status</th></tr></thead><tbody>{leads.map(lead => <tr key={lead.id} className="border-b border-slate-800/70"><td className="p-4 font-medium text-white">{lead.name}<span className="mt-1 block font-normal text-slate-500">{lead.address ?? "No address"}</span></td><td className="text-slate-300">{lead.category ?? "—"}</td><td className="text-slate-300">{lead.phone ?? lead.website ?? "—"}</td><td><select disabled={disabled} value={lead.status} onChange={e => onMove(lead, e.target.value as LeadStatus)} className="rounded border border-slate-700 bg-slate-950 px-2 py-1 text-white">{statuses.map(status => <option key={status}>{status}</option>)}</select></td></tr>)}{!leads.length && <tr><td colSpan={4} className="p-10 text-center text-slate-500">No saved leads yet. Search a configured live provider.</td></tr>}</tbody></table></section> }
function Pipeline({ columns, onMove, disabled }: { columns: Record<LeadStatus, Lead[]> | null; onMove: (lead: Lead, status: LeadStatus) => void; disabled: boolean }) { return <section className="grid gap-4 overflow-x-auto md:grid-cols-5">{statuses.map(status => <div key={status} className="min-h-72 min-w-52 rounded-xl border border-slate-800 bg-slate-900 p-3"><h2 className="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-400">{status} · {columns?.[status]?.length ?? 0}</h2>{columns?.[status]?.map(lead => <article key={lead.id} className="mb-2 rounded-lg border border-slate-700 bg-slate-950 p-3"><b className="text-sm text-white">{lead.name}</b><p className="mt-1 text-xs text-slate-500">{lead.category ?? "Uncategorized"}</p><select disabled={disabled} value={status} onChange={e => onMove(lead,e.target.value as LeadStatus)} className="mt-3 w-full rounded border border-slate-700 bg-slate-900 p-1 text-xs text-white">{statuses.map(next => <option key={next}>{next}</option>)}</select></article>)}</div>)}</section> }
