import type { Database } from "./db.js";
import type { DiscoveredBusiness } from "./providers/googlePlaces.js";

export type PersistedLead = { id: string; organizationId: string; source: string; sourceId: string; name: string; category: string | null; address: string | null; city: string | null; region: string | null; country: string | null; phone: string | null; website: string | null; latitude: number | null; longitude: number | null; status: "new" | "contacted" | "qualified" | "disqualified" | "converted"; ownerId: string | null; metadata: Record<string, unknown>; createdAt: string; updatedAt: string };
export const mapLeadRow = (r: Record<string, unknown>): PersistedLead => ({ id: String(r.id), organizationId: String(r.organization_id), source: String(r.source), sourceId: String(r.source_id), name: String(r.name), category: r.category as string | null, address: r.address as string | null, city: r.city as string | null, region: r.region as string | null, country: r.country as string | null, phone: r.phone as string | null, website: r.website as string | null, latitude: r.latitude as number | null, longitude: r.longitude as number | null, status: r.status as PersistedLead["status"], ownerId: r.owner_id as string | null, metadata: r.metadata as Record<string, unknown>, createdAt: new Date(String(r.created_at)).toISOString(), updatedAt: new Date(String(r.updated_at)).toISOString() });
export class LeadRepository {
  constructor(private readonly db: Database) {}
  async upsertDiscovery(organizationId: string, source: string, business: DiscoveredBusiness): Promise<{ lead: PersistedLead; created: boolean }> {
    const result = await this.db.query(`INSERT INTO leads (organization_id,source,source_id,name,category,address,phone,website,latitude,longitude,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb) ON CONFLICT (organization_id,source,source_id) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,address=EXCLUDED.address,phone=EXCLUDED.phone,website=EXCLUDED.website,latitude=EXCLUDED.latitude,longitude=EXCLUDED.longitude,metadata=EXCLUDED.metadata,updated_at=now() RETURNING *, (xmax = 0) AS inserted`, [organizationId, source, business.sourceId, business.name, business.category, business.address, business.phone, business.website, business.latitude, business.longitude, JSON.stringify(business.metadata)]);
    const row = result.rows[0]; if (!row) throw new Error("lead upsert returned no record"); return { lead: mapLeadRow(row), created: row.inserted === true || row.inserted === "t" };
  }
  async recordSearch(input: { organizationId: string; userId: string; query: string; provider: string; limit: number; resultsReturned: number; newLeadsCreated: number; duplicatesDetected: number; errors?: string; durationMs: number }): Promise<void> {
    await this.db.query("INSERT INTO search_history (organization_id,user_id,query,provider,filters,results_returned,new_leads_created,duplicates_detected,errors,duration_ms) VALUES ($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9::jsonb,$10)", [input.organizationId,input.userId,input.query,input.provider,JSON.stringify({ limit: input.limit }),input.resultsReturned,input.newLeadsCreated,input.duplicatesDetected,input.errors ? JSON.stringify({ message: input.errors }) : null,input.durationMs]);
  }
}
