"use client";

import Image from "next/image";
import { useState, type FormEvent } from "react";

type Message = { from: "agent" | "user"; text: string };
const replyFor = (text: string) => { const value = text.toLowerCase(); if (value.includes("duplicate")) return "Open Intelligence to review secondary duplicate signals. Source plus stable provider ID is the primary identity rule; merge decisions always need a human."; if (value.includes("export")) return "Select leads in Discover or use Intelligence for a formula-safe CSV export. Every export is written to the activity ledger."; if (value.includes("admin") || value.includes("user")) return "Administrators can use Admin to create members, change roles, and deactivate access. Regular users can use Account to review their session."; if (value.includes("search")) return "Use Discover to search a city, category, or business type. A configured provider is required; Scout never fills an empty result with synthetic businesses."; return "I can guide you through Discover, Pipeline, Collections, Intelligence, exports, and access control. Ask about any of those areas."; };

export function AssistantWidget() {
  const [open, setOpen] = useState(false); const [input, setInput] = useState(""); const [messages, setMessages] = useState<Message[]>([{ from: "agent", text: "Hi, I’m Scout Guide. I can help you navigate the lead workspace." }]);
  const submit = (event: FormEvent) => { event.preventDefault(); const text = input.trim(); if (!text) return; setMessages(previous => [...previous, { from: "user", text }, { from: "agent", text: replyFor(text) }]); setInput(""); };
  return <div className="fixed bottom-5 right-5 z-30"><button onClick={() => setOpen(!open)} className="flex items-center gap-2 rounded-full border border-cyan-700 bg-slate-900 px-3 py-2 text-sm font-semibold text-white shadow-xl hover:border-cyan-400" aria-label="Open Scout Guide"><Image src="/images/ai-agent-avatar.png" alt="" width={32} height={32} className="rounded-full object-cover" />Scout Guide</button>{open && <section className="mb-3 w-[min(360px,calc(100vw-2rem))] overflow-hidden rounded-2xl border border-slate-700 bg-slate-950 shadow-2xl" aria-label="Scout Guide chat"><header className="flex items-center gap-3 border-b border-slate-800 bg-slate-900 p-4"><Image src="/images/ai-agent-avatar.png" alt="Scout Guide" width={42} height={42} className="rounded-xl object-cover" /><div><p className="font-semibold text-white">Scout Guide</p><p className="text-xs text-slate-500">Product guidance · no invented data</p></div><button onClick={() => setOpen(false)} className="ml-auto text-slate-500" aria-label="Close Scout Guide">×</button></header><div className="max-h-72 space-y-3 overflow-y-auto p-4">{messages.map((message, index) => <p key={`${message.from}-${index}`} className={`max-w-[88%] rounded-xl px-3 py-2 text-sm leading-5 ${message.from === "user" ? "ml-auto bg-cyan-400 text-slate-950" : "bg-slate-900 text-slate-300"}`}>{message.text}</p>)}</div><form onSubmit={submit} className="flex gap-2 border-t border-slate-800 p-3"><input value={input} onChange={event => setInput(event.target.value)} placeholder="Ask how to use Scout…" className="min-w-0 flex-1 rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white" /><button className="rounded-lg bg-cyan-400 px-3 py-2 text-sm font-semibold text-slate-950">Send</button></form></section>}</div>;
}
