-- SQLite mirror of football_intelligence.mysql.sql (offline dev runtime).
CREATE TABLE IF NOT EXISTS football_providers (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_code TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'NOT_CONFIGURED', capabilities TEXT, requests_used INTEGER NOT NULL DEFAULT 0, requests_used_date TEXT, requests_budget INTEGER, rate_limit_per_minute INTEGER, backoff_until TEXT, last_success_at TEXT, last_failure_at TEXT, last_error TEXT, demo_mode INTEGER NOT NULL DEFAULT 0, enabled INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS football_competitions (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_id INTEGER NOT NULL, external_id TEXT NOT NULL, name TEXT NOT NULL, country TEXT, code TEXT, season TEXT, tier INTEGER, coefficient REAL, reliability REAL, data_state TEXT NOT NULL DEFAULT 'DATA_UNAVAILABLE', payload TEXT, fetched_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(provider_id, external_id, season));
CREATE INDEX IF NOT EXISTS idx_football_competition_name ON football_competitions(name);

CREATE TABLE IF NOT EXISTS football_teams (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_id INTEGER NOT NULL, external_id TEXT NOT NULL, name TEXT NOT NULL, short_code TEXT, logo TEXT, venue TEXT, country TEXT, data_state TEXT NOT NULL DEFAULT 'DATA_UNAVAILABLE', payload TEXT, fetched_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(provider_id, external_id));
CREATE INDEX IF NOT EXISTS idx_football_team_name ON football_teams(name);

CREATE TABLE IF NOT EXISTS football_fixtures (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_id INTEGER NOT NULL, external_id TEXT NOT NULL, competition_id INTEGER, competition TEXT NOT NULL DEFAULT 'DATA_UNAVAILABLE', country TEXT, season TEXT, round TEXT, kickoff_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'SCHEDULED', match_state TEXT NOT NULL DEFAULT 'PRE_MATCH', minute INTEGER, extra_minute INTEGER, home_team TEXT NOT NULL, away_team TEXT NOT NULL, home_team_id TEXT, away_team_id TEXT, home_score INTEGER, away_score INTEGER, half_time_home INTEGER, half_time_away INTEGER, home_red_cards INTEGER, away_red_cards INTEGER, venue TEXT, data_state TEXT NOT NULL DEFAULT 'DATA_UNAVAILABLE', coverage TEXT, payload TEXT, source_timestamp TEXT NOT NULL, settled_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(provider_id, external_id));
CREATE INDEX IF NOT EXISTS idx_football_fixture_kickoff ON football_fixtures(kickoff_at);
CREATE INDEX IF NOT EXISTS idx_football_fixture_status ON football_fixtures(status, kickoff_at);
CREATE INDEX IF NOT EXISTS idx_football_fixture_settle ON football_fixtures(settled_at, status);

CREATE TABLE IF NOT EXISTS football_team_statistics (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_id INTEGER NOT NULL, team_external_id TEXT NOT NULL, competition_external_id TEXT, season TEXT, team TEXT NOT NULL, played INTEGER, wins INTEGER, draws INTEGER, losses INTEGER, goals_for INTEGER, goals_against INTEGER, points INTEGER, position INTEGER, home_played INTEGER, home_wins INTEGER, home_draws INTEGER, home_losses INTEGER, home_goals_for INTEGER, home_goals_against INTEGER, away_played INTEGER, away_wins INTEGER, away_draws INTEGER, away_losses INTEGER, away_goals_for INTEGER, away_goals_against INTEGER, clean_sheets INTEGER, failed_to_score INTEGER, form_last5 TEXT, form_last10 TEXT, last_matches TEXT, data_state TEXT NOT NULL DEFAULT 'DATA_UNAVAILABLE', coverage TEXT, payload TEXT, fetched_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(provider_id, team_external_id, competition_external_id, season));
CREATE INDEX IF NOT EXISTS idx_football_team_stats_team ON football_team_statistics(team_external_id, fetched_at);

CREATE TABLE IF NOT EXISTS football_fixture_statistics (id INTEGER PRIMARY KEY AUTOINCREMENT, fixture_id INTEGER NOT NULL, provider_id INTEGER NOT NULL, kind TEXT NOT NULL DEFAULT 'MATCH', payload TEXT NOT NULL, data_state TEXT NOT NULL DEFAULT 'DATA_UNAVAILABLE', coverage TEXT, fetched_at TEXT, created_at TEXT NOT NULL, UNIQUE(fixture_id, provider_id, kind));
CREATE INDEX IF NOT EXISTS idx_football_fixture_stat_fetch ON football_fixture_statistics(fetched_at);

CREATE TABLE IF NOT EXISTS football_head_to_head (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_id INTEGER NOT NULL, home_team_external_id TEXT NOT NULL, away_team_external_id TEXT NOT NULL, competition_external_id TEXT, meetings INTEGER NOT NULL DEFAULT 0, home_wins INTEGER NOT NULL DEFAULT 0, draws INTEGER NOT NULL DEFAULT 0, away_wins INTEGER NOT NULL DEFAULT 0, avg_home_goals REAL, avg_away_goals REAL, both_teams_scored INTEGER, over_15 INTEGER, over_25 INTEGER, oldest_kickoff TEXT, newest_kickoff TEXT, sample_age_days INTEGER, weight REAL NOT NULL DEFAULT 0.0, data_state TEXT NOT NULL DEFAULT 'DATA_UNAVAILABLE', matches TEXT, fetched_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(provider_id, home_team_external_id, away_team_external_id, competition_external_id));
CREATE INDEX IF NOT EXISTS idx_football_h2h_fetch ON football_head_to_head(fetched_at);

CREATE TABLE IF NOT EXISTS football_model_versions (id INTEGER PRIMARY KEY AUTOINCREMENT, model_id TEXT NOT NULL, model_name TEXT NOT NULL, model_version TEXT NOT NULL, algorithm TEXT NOT NULL DEFAULT 'poisson-dixon-coles', feature_version TEXT NOT NULL, training_dataset_version TEXT, status TEXT NOT NULL DEFAULT 'DRAFT', created_at TEXT NOT NULL, trained_at TEXT, validated_at TEXT, calibrated_at TEXT, approved_at TEXT, approved_by TEXT, activated_at TEXT, activated_by TEXT, retired_at TEXT, last_evaluated_at TEXT, calibration_version_id INTEGER, validation_sample_size INTEGER, training_sample_size INTEGER, accuracy REAL, log_loss REAL, brier_score REAL, ece REAL, parameters TEXT, lifecycle_history TEXT, rejection_reason TEXT, updated_at TEXT NOT NULL, UNIQUE(model_name, model_version));
CREATE INDEX IF NOT EXISTS idx_football_model_status ON football_model_versions(status, updated_at);

CREATE TABLE IF NOT EXISTS football_calibration_versions (id INTEGER PRIMARY KEY AUTOINCREMENT, model_version_id INTEGER NOT NULL, calibration_version TEXT NOT NULL, method TEXT NOT NULL DEFAULT 'platt', parameters TEXT NOT NULL, sample_size INTEGER NOT NULL DEFAULT 0, accuracy REAL, log_loss REAL, brier REAL, ece REAL, mce REAL, reliability_bins TEXT, training_window_start TEXT, training_window_end TEXT, status TEXT NOT NULL DEFAULT 'PENDING', created_by TEXT, approved_by TEXT, approved_at TEXT, rejected_by TEXT, rejected_at TEXT, reason TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(model_version_id, calibration_version));
CREATE INDEX IF NOT EXISTS idx_football_calibration_status ON football_calibration_versions(model_version_id, status, created_at);

CREATE TABLE IF NOT EXISTS football_match_predictions (id TEXT PRIMARY KEY, fixture_id INTEGER NOT NULL, provider_id INTEGER NOT NULL, model_version_id INTEGER, calibration_version_id INTEGER, calibration_state TEXT NOT NULL DEFAULT 'CALIBRATION_PENDING', prediction_kind TEXT NOT NULL DEFAULT 'PRE_MATCH', supersedes_prediction_id TEXT, generated_at TEXT NOT NULL, kickoff_at TEXT NOT NULL, status_at_prediction TEXT NOT NULL DEFAULT 'SCHEDULED', predicted_result TEXT NOT NULL, predicted_home_score INTEGER, predicted_away_score INTEGER, probability_home REAL, probability_draw REAL, probability_away REAL, raw_home REAL, raw_draw REAL, raw_away REAL, expected_total_goals REAL, confidence REAL, confidence_basis TEXT, data_quality_score INTEGER NOT NULL DEFAULT 0, data_quality_band TEXT NOT NULL DEFAULT 'REJECTED', quality_components TEXT, feature_snapshot TEXT NOT NULL, probabilities_matrix TEXT, alternative_scores TEXT, reason TEXT, evidence TEXT, outcome TEXT, eligibility TEXT NOT NULL DEFAULT 'QUALIFIED', rejection_reasons TEXT, settlement_state TEXT NOT NULL DEFAULT 'OPEN', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(fixture_id, prediction_kind, model_version_id));
CREATE INDEX IF NOT EXISTS idx_football_prediction_generated ON football_match_predictions(generated_at);
CREATE INDEX IF NOT EXISTS idx_football_prediction_settle ON football_match_predictions(settlement_state, generated_at);
CREATE INDEX IF NOT EXISTS idx_football_prediction_model ON football_match_predictions(model_version_id, settlement_state);

CREATE TABLE IF NOT EXISTS football_score_probabilities (id INTEGER PRIMARY KEY AUTOINCREMENT, prediction_id TEXT NOT NULL, home_goals INTEGER NOT NULL, away_goals INTEGER NOT NULL, probability REAL NOT NULL, rank INTEGER NOT NULL DEFAULT 0, is_prediction INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, UNIQUE(prediction_id, home_goals, away_goals));
CREATE INDEX IF NOT EXISTS idx_football_score_rank ON football_score_probabilities(prediction_id, rank);

CREATE TABLE IF NOT EXISTS football_prediction_settlements (id INTEGER PRIMARY KEY AUTOINCREMENT, prediction_id TEXT NOT NULL, fixture_id INTEGER NOT NULL, actual_home_score INTEGER, actual_away_score INTEGER, actual_result TEXT NOT NULL, predicted_result TEXT NOT NULL, predicted_home_score INTEGER, predicted_away_score INTEGER, probability_home REAL, probability_draw REAL, probability_away REAL, confidence REAL, data_quality_score INTEGER, model_version_id INTEGER, calibration_version_id INTEGER, correct_result INTEGER, correct_exact_score INTEGER, brier REAL, log_loss REAL, absolute_goal_error REAL, result_source TEXT NOT NULL DEFAULT 'PROVIDER', settled_at TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(prediction_id));
CREATE INDEX IF NOT EXISTS idx_football_settlement_fixture ON football_prediction_settlements(fixture_id);
CREATE INDEX IF NOT EXISTS idx_football_settlement_settled ON football_prediction_settlements(settled_at);

CREATE TABLE IF NOT EXISTS football_model_performance (id INTEGER PRIMARY KEY AUTOINCREMENT, model_version_id INTEGER, calibration_version_id INTEGER, window_days INTEGER NOT NULL DEFAULT 30, window_start TEXT NOT NULL, window_end TEXT NOT NULL, evaluated_predictions INTEGER NOT NULL DEFAULT 0, correct_results INTEGER NOT NULL DEFAULT 0, correct_scores INTEGER NOT NULL DEFAULT 0, result_accuracy REAL, exact_score_accuracy REAL, average_confidence REAL, average_data_quality REAL, brier REAL, ece REAL, log_loss REAL, payload TEXT NOT NULL, computed_at TEXT NOT NULL, UNIQUE(model_version_id, window_days, window_start, window_end));
CREATE INDEX IF NOT EXISTS idx_football_perf_computed ON football_model_performance(computed_at);

CREATE TABLE IF NOT EXISTS football_provider_sync_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_id INTEGER, provider_code TEXT, job_type TEXT NOT NULL, status TEXT NOT NULL, execution_key TEXT NOT NULL, window_start TEXT, window_end TEXT, records_processed INTEGER NOT NULL DEFAULT 0, records_created INTEGER NOT NULL DEFAULT 0, records_updated INTEGER NOT NULL DEFAULT 0, requests_made INTEGER NOT NULL DEFAULT 0, rate_limit_remaining INTEGER, retry_after_seconds INTEGER, next_run_at TEXT, attempts INTEGER NOT NULL DEFAULT 1, errors TEXT, started_at TEXT NOT NULL, ended_at TEXT, UNIQUE(execution_key));
CREATE INDEX IF NOT EXISTS idx_football_sync_job ON football_provider_sync_logs(job_type, started_at);
