-- PostgreSQL schema — generated from football_intelligence.mysql.sql by tools/generate_pgsql_schema.mjs.
-- Column sets are identical to the canonical MySQL schema; types are the closest
-- PostgreSQL equivalents (TINYINT→SMALLINT, DATETIME→TIMESTAMP, LONGTEXT→TEXT, JSON→JSONB).

CREATE TABLE IF NOT EXISTS "football_providers" (
  "id" SERIAL PRIMARY KEY,
  "provider_code" VARCHAR(64) NOT NULL UNIQUE,
  "display_name" VARCHAR(120) NOT NULL,
  "status" VARCHAR(24) NOT NULL DEFAULT 'NOT_CONFIGURED',
  "capabilities" TEXT NULL,
  "requests_used" INTEGER NOT NULL DEFAULT 0,
  "requests_used_date" DATE NULL,
  "requests_budget" INTEGER NULL,
  "rate_limit_per_minute" INTEGER NULL,
  "backoff_until" VARCHAR(32) NULL,
  "last_success_at" VARCHAR(32) NULL,
  "last_failure_at" VARCHAR(32) NULL,
  "last_error" VARCHAR(500) NULL,
  "demo_mode" SMALLINT NOT NULL DEFAULT 0,
  "enabled" SMALLINT NOT NULL DEFAULT 0,
  "created_at" VARCHAR(32) NOT NULL,
  "updated_at" VARCHAR(32) NOT NULL
);
CREATE TABLE IF NOT EXISTS "football_competitions" (
  "id" SERIAL PRIMARY KEY,
  "provider_id" INTEGER NOT NULL,
  "external_id" VARCHAR(64) NOT NULL,
  "name" VARCHAR(160) NOT NULL,
  "country" VARCHAR(80) NULL,
  "code" VARCHAR(32) NULL,
  "season" VARCHAR(16) NULL,
  "tier" INTEGER NULL,
  "coefficient" DECIMAL(8,4) NULL,
  "reliability" DECIMAL(5,2) NULL,
  "data_state" VARCHAR(24) NOT NULL DEFAULT 'DATA_UNAVAILABLE',
  "payload" TEXT NULL,
  "fetched_at" VARCHAR(32) NULL,
  "created_at" VARCHAR(32) NOT NULL,
  "updated_at" VARCHAR(32) NOT NULL,
  CONSTRAINT "uq_football_competition" UNIQUE ("provider_id", "external_id", "season")
);
CREATE INDEX IF NOT EXISTS "idx_football_competition_name" ON "football_competitions" ("name");
CREATE TABLE IF NOT EXISTS "football_teams" (
  "id" SERIAL PRIMARY KEY,
  "provider_id" INTEGER NOT NULL,
  "external_id" VARCHAR(64) NOT NULL,
  "name" VARCHAR(160) NOT NULL,
  "short_code" VARCHAR(16) NULL,
  "logo" VARCHAR(255) NULL,
  "venue" VARCHAR(160) NULL,
  "country" VARCHAR(80) NULL,
  "data_state" VARCHAR(24) NOT NULL DEFAULT 'DATA_UNAVAILABLE',
  "payload" TEXT NULL,
  "fetched_at" VARCHAR(32) NULL,
  "created_at" VARCHAR(32) NOT NULL,
  "updated_at" VARCHAR(32) NOT NULL,
  CONSTRAINT "uq_football_team" UNIQUE ("provider_id", "external_id")
);
CREATE INDEX IF NOT EXISTS "idx_football_team_name" ON "football_teams" ("name");
CREATE TABLE IF NOT EXISTS "football_fixtures" (
  "id" BIGSERIAL PRIMARY KEY,
  "provider_id" INTEGER NOT NULL,
  "external_id" VARCHAR(64) NOT NULL,
  "competition_id" INTEGER NULL,
  "competition" VARCHAR(160) NOT NULL DEFAULT 'DATA_UNAVAILABLE',
  "country" VARCHAR(80) NULL,
  "season" VARCHAR(16) NULL,
  "round" VARCHAR(64) NULL,
  "kickoff_at" VARCHAR(32) NOT NULL,
  "status" VARCHAR(24) NOT NULL DEFAULT 'SCHEDULED',
  "match_state" VARCHAR(32) NOT NULL DEFAULT 'PRE_MATCH',
  "minute" INTEGER NULL,
  "extra_minute" INTEGER NULL,
  "home_team" VARCHAR(160) NOT NULL,
  "away_team" VARCHAR(160) NOT NULL,
  "home_team_id" VARCHAR(64) NULL,
  "away_team_id" VARCHAR(64) NULL,
  "home_score" INTEGER NULL,
  "away_score" INTEGER NULL,
  "half_time_home" INTEGER NULL,
  "half_time_away" INTEGER NULL,
  "home_red_cards" INTEGER NULL,
  "away_red_cards" INTEGER NULL,
  "venue" VARCHAR(160) NULL,
  "data_state" VARCHAR(24) NOT NULL DEFAULT 'DATA_UNAVAILABLE',
  "coverage" TEXT NULL,
  "payload" TEXT NULL,
  "source_timestamp" VARCHAR(32) NOT NULL,
  "settled_at" VARCHAR(32) NULL,
  "created_at" VARCHAR(32) NOT NULL,
  "updated_at" VARCHAR(32) NOT NULL,
  CONSTRAINT "uq_football_fixture" UNIQUE ("provider_id", "external_id")
);
CREATE INDEX IF NOT EXISTS "idx_football_fixture_kickoff" ON "football_fixtures" ("kickoff_at");
CREATE INDEX IF NOT EXISTS "idx_football_fixture_status" ON "football_fixtures" ("status", "kickoff_at");
CREATE INDEX IF NOT EXISTS "idx_football_fixture_settle" ON "football_fixtures" ("settled_at", "status");
CREATE TABLE IF NOT EXISTS "football_team_statistics" (
  "id" BIGSERIAL PRIMARY KEY,
  "provider_id" INTEGER NOT NULL,
  "team_external_id" VARCHAR(64) NOT NULL,
  "competition_external_id" VARCHAR(64) NULL,
  "season" VARCHAR(16) NULL,
  "team" VARCHAR(160) NOT NULL,
  "played" INTEGER NULL,
  "wins" INTEGER NULL,
  "draws" INTEGER NULL,
  "losses" INTEGER NULL,
  "goals_for" INTEGER NULL,
  "goals_against" INTEGER NULL,
  "points" INTEGER NULL,
  "position" INTEGER NULL,
  "home_played" INTEGER NULL,
  "home_wins" INTEGER NULL,
  "home_draws" INTEGER NULL,
  "home_losses" INTEGER NULL,
  "home_goals_for" INTEGER NULL,
  "home_goals_against" INTEGER NULL,
  "away_played" INTEGER NULL,
  "away_wins" INTEGER NULL,
  "away_draws" INTEGER NULL,
  "away_losses" INTEGER NULL,
  "away_goals_for" INTEGER NULL,
  "away_goals_against" INTEGER NULL,
  "clean_sheets" INTEGER NULL,
  "failed_to_score" INTEGER NULL,
  "form_last5" VARCHAR(20) NULL,
  "form_last10" VARCHAR(40) NULL,
  "last_matches" TEXT NULL,
  "data_state" VARCHAR(24) NOT NULL DEFAULT 'DATA_UNAVAILABLE',
  "coverage" TEXT NULL,
  "payload" TEXT NULL,
  "fetched_at" VARCHAR(32) NULL,
  "created_at" VARCHAR(32) NOT NULL,
  "updated_at" VARCHAR(32) NOT NULL,
  CONSTRAINT "uq_football_team_stats" UNIQUE ("provider_id", "team_external_id", "competition_external_id", "season")
);
CREATE INDEX IF NOT EXISTS "idx_football_team_stats_team" ON "football_team_statistics" ("team_external_id", "fetched_at");
CREATE TABLE IF NOT EXISTS "football_fixture_statistics" (
  "id" BIGSERIAL PRIMARY KEY,
  "fixture_id" BIGINT NOT NULL,
  "provider_id" INTEGER NOT NULL,
  "kind" VARCHAR(32) NOT NULL DEFAULT 'MATCH',
  "payload" TEXT NOT NULL,
  "data_state" VARCHAR(24) NOT NULL DEFAULT 'DATA_UNAVAILABLE',
  "coverage" TEXT NULL,
  "fetched_at" VARCHAR(32) NULL,
  "created_at" VARCHAR(32) NOT NULL,
  CONSTRAINT "uq_football_fixture_stat" UNIQUE ("fixture_id", "provider_id", "kind")
);
CREATE INDEX IF NOT EXISTS "idx_football_fixture_stat_fetch" ON "football_fixture_statistics" ("fetched_at");
CREATE TABLE IF NOT EXISTS "football_head_to_head" (
  "id" BIGSERIAL PRIMARY KEY,
  "provider_id" INTEGER NOT NULL,
  "home_team_external_id" VARCHAR(64) NOT NULL,
  "away_team_external_id" VARCHAR(64) NOT NULL,
  "competition_external_id" VARCHAR(64) NULL,
  "meetings" INTEGER NOT NULL DEFAULT 0,
  "home_wins" INTEGER NOT NULL DEFAULT 0,
  "draws" INTEGER NOT NULL DEFAULT 0,
  "away_wins" INTEGER NOT NULL DEFAULT 0,
  "avg_home_goals" DECIMAL(6,3) NULL,
  "avg_away_goals" DECIMAL(6,3) NULL,
  "both_teams_scored" INTEGER NULL,
  "over_15" INTEGER NULL,
  "over_25" INTEGER NULL,
  "oldest_kickoff" VARCHAR(32) NULL,
  "newest_kickoff" VARCHAR(32) NULL,
  "sample_age_days" INTEGER NULL,
  "weight" DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
  "data_state" VARCHAR(24) NOT NULL DEFAULT 'DATA_UNAVAILABLE',
  "matches" TEXT NULL,
  "fetched_at" VARCHAR(32) NULL,
  "created_at" VARCHAR(32) NOT NULL,
  "updated_at" VARCHAR(32) NOT NULL,
  CONSTRAINT "uq_football_h2h" UNIQUE ("provider_id", "home_team_external_id", "away_team_external_id", "competition_external_id")
);
CREATE INDEX IF NOT EXISTS "idx_football_h2h_fetch" ON "football_head_to_head" ("fetched_at");
CREATE TABLE IF NOT EXISTS "football_model_versions" (
  "id" SERIAL PRIMARY KEY,
  "model_id" VARCHAR(64) NOT NULL,
  "model_name" VARCHAR(120) NOT NULL,
  "model_version" VARCHAR(64) NOT NULL,
  "algorithm" VARCHAR(64) NOT NULL DEFAULT 'poisson-dixon-coles',
  "feature_version" VARCHAR(64) NOT NULL,
  "training_dataset_version" VARCHAR(64) NULL,
  "status" VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
  "created_at" VARCHAR(32) NOT NULL,
  "trained_at" VARCHAR(32) NULL,
  "validated_at" VARCHAR(32) NULL,
  "calibrated_at" VARCHAR(32) NULL,
  "approved_at" VARCHAR(32) NULL,
  "approved_by" VARCHAR(64) NULL,
  "activated_at" VARCHAR(32) NULL,
  "activated_by" VARCHAR(64) NULL,
  "retired_at" VARCHAR(32) NULL,
  "last_evaluated_at" VARCHAR(32) NULL,
  "calibration_version_id" INTEGER NULL,
  "validation_sample_size" INTEGER NULL,
  "training_sample_size" INTEGER NULL,
  "accuracy" DECIMAL(8,5) NULL,
  "log_loss" DECIMAL(10,6) NULL,
  "brier_score" DECIMAL(10,6) NULL,
  "ece" DECIMAL(10,6) NULL,
  "parameters" TEXT NULL,
  "lifecycle_history" TEXT NULL,
  "rejection_reason" VARCHAR(500) NULL,
  "updated_at" VARCHAR(32) NOT NULL,
  CONSTRAINT "uq_football_model" UNIQUE ("model_name", "model_version")
);
CREATE INDEX IF NOT EXISTS "idx_football_model_status" ON "football_model_versions" ("status", "updated_at");
CREATE TABLE IF NOT EXISTS "football_calibration_versions" (
  "id" SERIAL PRIMARY KEY,
  "model_version_id" INTEGER NOT NULL,
  "calibration_version" VARCHAR(64) NOT NULL,
  "method" VARCHAR(32) NOT NULL DEFAULT 'platt',
  "parameters" TEXT NOT NULL,
  "sample_size" INTEGER NOT NULL DEFAULT 0,
  "accuracy" DECIMAL(8,5) NULL,
  "log_loss" DECIMAL(10,6) NULL,
  "brier" DECIMAL(10,6) NULL,
  "ece" DECIMAL(10,6) NULL,
  "mce" DECIMAL(10,6) NULL,
  "reliability_bins" TEXT NULL,
  "training_window_start" VARCHAR(32) NULL,
  "training_window_end" VARCHAR(32) NULL,
  "status" VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  "created_by" VARCHAR(64) NULL,
  "approved_by" VARCHAR(64) NULL,
  "approved_at" VARCHAR(32) NULL,
  "rejected_by" VARCHAR(64) NULL,
  "rejected_at" VARCHAR(32) NULL,
  "reason" VARCHAR(500) NULL,
  "created_at" VARCHAR(32) NOT NULL,
  "updated_at" VARCHAR(32) NOT NULL,
  CONSTRAINT "uq_football_calibration" UNIQUE ("model_version_id", "calibration_version")
);
CREATE INDEX IF NOT EXISTS "idx_football_calibration_status" ON "football_calibration_versions" ("model_version_id", "status", "created_at");
CREATE TABLE IF NOT EXISTS "football_match_predictions" (
  "id" VARCHAR(40) PRIMARY KEY,
  "fixture_id" BIGINT NOT NULL,
  "provider_id" INTEGER NOT NULL,
  "model_version_id" INTEGER NULL,
  "calibration_version_id" INTEGER NULL,
  "calibration_state" VARCHAR(24) NOT NULL DEFAULT 'CALIBRATION_PENDING',
  "prediction_kind" VARCHAR(16) NOT NULL DEFAULT 'PRE_MATCH',
  "supersedes_prediction_id" VARCHAR(40) NULL,
  "generated_at" VARCHAR(32) NOT NULL,
  "kickoff_at" VARCHAR(32) NOT NULL,
  "status_at_prediction" VARCHAR(24) NOT NULL DEFAULT 'SCHEDULED',
  "predicted_result" VARCHAR(24) NOT NULL,
  "predicted_home_score" INTEGER NULL,
  "predicted_away_score" INTEGER NULL,
  "probability_home" DECIMAL(8,6) NULL,
  "probability_draw" DECIMAL(8,6) NULL,
  "probability_away" DECIMAL(8,6) NULL,
  "raw_home" DECIMAL(8,6) NULL,
  "raw_draw" DECIMAL(8,6) NULL,
  "raw_away" DECIMAL(8,6) NULL,
  "expected_total_goals" DECIMAL(6,3) NULL,
  "confidence" DECIMAL(6,2) NULL,
  "confidence_basis" VARCHAR(32) NULL,
  "data_quality_score" INTEGER NOT NULL DEFAULT 0,
  "data_quality_band" VARCHAR(16) NOT NULL DEFAULT 'REJECTED',
  "quality_components" TEXT NULL,
  "feature_snapshot" TEXT NOT NULL,
  "probabilities_matrix" TEXT NULL,
  "alternative_scores" TEXT NULL,
  "reason" VARCHAR(600) NULL,
  "evidence" TEXT NULL,
  "outcome" VARCHAR(600) NULL,
  "eligibility" VARCHAR(24) NOT NULL DEFAULT 'QUALIFIED',
  "rejection_reasons" TEXT NULL,
  "settlement_state" VARCHAR(16) NOT NULL DEFAULT 'OPEN',
  "created_at" VARCHAR(32) NOT NULL,
  "updated_at" VARCHAR(32) NOT NULL,
  CONSTRAINT "uq_football_prediction_kind" UNIQUE ("fixture_id", "prediction_kind", "model_version_id")
);
CREATE INDEX IF NOT EXISTS "idx_football_prediction_generated" ON "football_match_predictions" ("generated_at");
CREATE INDEX IF NOT EXISTS "idx_football_prediction_settle" ON "football_match_predictions" ("settlement_state", "generated_at");
CREATE INDEX IF NOT EXISTS "idx_football_prediction_model" ON "football_match_predictions" ("model_version_id", "settlement_state");
CREATE TABLE IF NOT EXISTS "football_score_probabilities" (
  "id" BIGSERIAL PRIMARY KEY,
  "prediction_id" VARCHAR(40) NOT NULL,
  "home_goals" INTEGER NOT NULL,
  "away_goals" INTEGER NOT NULL,
  "probability" DECIMAL(8,6) NOT NULL,
  "rank" INTEGER NOT NULL DEFAULT 0,
  "is_prediction" SMALLINT NOT NULL DEFAULT 0,
  "created_at" VARCHAR(32) NOT NULL,
  CONSTRAINT "uq_football_score_row" UNIQUE ("prediction_id", "home_goals", "away_goals")
);
CREATE INDEX IF NOT EXISTS "idx_football_score_rank" ON "football_score_probabilities" ("prediction_id", "rank");
CREATE TABLE IF NOT EXISTS "football_prediction_settlements" (
  "id" BIGSERIAL PRIMARY KEY,
  "prediction_id" VARCHAR(40) NOT NULL,
  "fixture_id" BIGINT NOT NULL,
  "actual_home_score" INTEGER NULL,
  "actual_away_score" INTEGER NULL,
  "actual_result" VARCHAR(24) NOT NULL,
  "predicted_result" VARCHAR(24) NOT NULL,
  "predicted_home_score" INTEGER NULL,
  "predicted_away_score" INTEGER NULL,
  "probability_home" DECIMAL(8,6) NULL,
  "probability_draw" DECIMAL(8,6) NULL,
  "probability_away" DECIMAL(8,6) NULL,
  "confidence" DECIMAL(6,2) NULL,
  "data_quality_score" INTEGER NULL,
  "model_version_id" INTEGER NULL,
  "calibration_version_id" INTEGER NULL,
  "correct_result" SMALLINT NULL,
  "correct_exact_score" SMALLINT NULL,
  "brier" DECIMAL(10,6) NULL,
  "log_loss" DECIMAL(10,6) NULL,
  "absolute_goal_error" DECIMAL(8,3) NULL,
  "result_source" VARCHAR(32) NOT NULL DEFAULT 'PROVIDER',
  "settled_at" VARCHAR(32) NOT NULL,
  "created_at" VARCHAR(32) NOT NULL,
  CONSTRAINT "uq_football_settlement_prediction" UNIQUE ("prediction_id")
);
CREATE INDEX IF NOT EXISTS "idx_football_settlement_fixture" ON "football_prediction_settlements" ("fixture_id");
CREATE INDEX IF NOT EXISTS "idx_football_settlement_settled" ON "football_prediction_settlements" ("settled_at");
CREATE TABLE IF NOT EXISTS "football_model_performance" (
  "id" BIGSERIAL PRIMARY KEY,
  "model_version_id" INTEGER NULL,
  "calibration_version_id" INTEGER NULL,
  "window_days" INTEGER NOT NULL DEFAULT 30,
  "window_start" VARCHAR(32) NOT NULL,
  "window_end" VARCHAR(32) NOT NULL,
  "evaluated_predictions" INTEGER NOT NULL DEFAULT 0,
  "correct_results" INTEGER NOT NULL DEFAULT 0,
  "correct_scores" INTEGER NOT NULL DEFAULT 0,
  "result_accuracy" DECIMAL(8,5) NULL,
  "exact_score_accuracy" DECIMAL(8,5) NULL,
  "average_confidence" DECIMAL(8,4) NULL,
  "average_data_quality" DECIMAL(8,4) NULL,
  "brier" DECIMAL(10,6) NULL,
  "ece" DECIMAL(10,6) NULL,
  "log_loss" DECIMAL(10,6) NULL,
  "payload" TEXT NOT NULL,
  "computed_at" VARCHAR(32) NOT NULL,
  CONSTRAINT "uq_football_perf" UNIQUE ("model_version_id", "window_days", "window_start", "window_end")
);
CREATE INDEX IF NOT EXISTS "idx_football_perf_computed" ON "football_model_performance" ("computed_at");
CREATE TABLE IF NOT EXISTS "football_provider_sync_logs" (
  "id" BIGSERIAL PRIMARY KEY,
  "provider_id" INTEGER NULL,
  "provider_code" VARCHAR(64) NULL,
  "job_type" VARCHAR(48) NOT NULL,
  "status" VARCHAR(24) NOT NULL,
  "execution_key" VARCHAR(190) NOT NULL,
  "window_start" VARCHAR(32) NULL,
  "window_end" VARCHAR(32) NULL,
  "records_processed" INTEGER NOT NULL DEFAULT 0,
  "records_created" INTEGER NOT NULL DEFAULT 0,
  "records_updated" INTEGER NOT NULL DEFAULT 0,
  "requests_made" INTEGER NOT NULL DEFAULT 0,
  "rate_limit_remaining" INTEGER NULL,
  "retry_after_seconds" INTEGER NULL,
  "next_run_at" VARCHAR(32) NULL,
  "attempts" INTEGER NOT NULL DEFAULT 1,
  "errors" TEXT NULL,
  "started_at" VARCHAR(32) NOT NULL,
  "ended_at" VARCHAR(32) NULL,
  CONSTRAINT "uq_football_sync_key" UNIQUE ("execution_key")
);
CREATE INDEX IF NOT EXISTS "idx_football_sync_job" ON "football_provider_sync_logs" ("job_type", "started_at");
