<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<div class="page-head"><div><h2>My Trading</h2><p>AI-assisted trading workspace. Orders remain subject to risk controls and approval.</p></div><a class="btn primary" href="/brokers">Manage accounts</a></div>
<?php if (!empty($notice)): ?><div class="notice ok"><?=e($notice)?></div><?php endif; ?><?php if (!empty($error)): ?><div class="notice err"><?=e($error)?></div><?php endif; ?>
<div class="notice <?= !empty($status['killSwitch']['active'])?'err':'ok' ?>"><b><?=!empty($status['killSwitch']['active'])?'Kill switch active':'Trading safeguards active'?></b> · Mode: <?=e($status['tradingMode']??'ANALYSIS_ONLY')?> · <?=count($connections)?> account connection(s)</div>
<nav class="tabs" style="margin:14px 0"><a href="#overview">Overview</a><a href="#trade">Trade</a><a href="#positions">Positions</a><a href="#accounts">Accounts</a><a href="#analysis">AI Analysis</a></nav>
<section id="overview" class="grid cols-main"><div class="panel"><h3>Portfolio overview</h3><div class="body"><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(150px,1fr))"><?php foreach($accounts as $a): ?><div class="card"><div class="dim"><?=e($a['label']??$a['broker'])?></div><strong><?=isset($a['equity'])?e(number_format((float)$a['equity'],2)):e($a['error']??'Unavailable')?></strong><div class="dim"><?=e($a['currency']??'')?></div></div><?php endforeach; if(!$accounts): ?><p class="dim">No connected account yet. Connect a demo account to begin.</p><?php endif; ?></div></div></div><div class="panel"><h3>System health</h3><div class="body"><p>AI providers: <b><?=count($analysis)?></b></p><p>Open positions: <b><?=count($positions)?></b></p><a class="btn" href="/execution">Open execution supervisor</a></div></div></section>
<section id="trade" class="panel" style="margin-top:14px"><h3>Trade with AI supervision</h3><div class="body"><p class="dim">Create a proposal in the Execution Center. The AI risk engine, kill switch, account gates and approval workflow run before any order can reach a broker.</p><a class="btn primary" href="/execution">Create trade proposal</a> <a class="btn" href="/analysis">Open AI Workforce</a></div></section>
<section id="positions" class="panel" style="margin-top:14px"><h3>Open positions</h3><div class="body"><table class="tbl"><thead><tr><th>Broker</th><th>Symbol</th><th>Side</th><th>Volume</th><th>P&amp;L</th></tr></thead><tbody><?php foreach($positions as $p): ?><tr><td><?=e($p['broker']??'')?></td><td><?=e($p['symbol']??'')?></td><td><?=e($p['side']??'')?></td><td><?=e((string)($p['volume']??''))?></td><td><?=e((string)($p['unrealizedPnl']??$p['pnl']??'—'))?></td></tr><?php endforeach; if(!$positions): ?><tr><td colspan="5" class="dim">No open positions.</td></tr><?php endif; ?></tbody></table></div></section>
<section id="accounts" class="panel" style="margin-top:14px"><h3>Connected accounts</h3><div class="body"><table class="tbl"><thead><tr><th>Platform</th><th>Label</th><th>Status</th><th>Mode</th><th></th></tr></thead><tbody><?php foreach($connections as $c): ?><tr><td><?=e($c['broker'])?></td><td><?=e($c['label']??'')?></td><td><?=!empty($c['enabled'])?'<span class="badge b-green">enabled</span>':'<span class="badge b-gray">disabled</span>'?></td><td><?=!empty($c['trading_enabled'])?'assisted':'analysis only'?></td><td><a class="btn" href="/brokers/connect/<?=e($c['broker'])?>">manage</a></td></tr><?php endforeach; ?></tbody></table><a class="btn primary" href="/brokers">Connect a platform</a></div></section>
<section id="analysis" class="panel" style="margin-top:14px"><h3>AI analysis</h3><div class="body"><p>Use the existing AI Workforce analysis and execution safeguards to review markets before submitting a trade.</p><a class="btn primary" href="/analysis">View AI recommendations</a></div></section>
