import type { BusinessSearchInput, BusinessSearchResult, Lead, LeadStatus, PipelineSummary } from "../../../../packages/shared/src/leadDiscovery";
const baseUrl = process.env.NEXT_PUBLIC_LEAD_API_URL ?? "http://localhost:3001/api/v1/lead-discovery";
type RequestOptions = RequestInit & { token?: string };
async function request<T>(path: string, options: RequestOptions = {}): Promise<T> { const { token, ...init } = options; const response = await fetch(`${baseUrl}${path}`, { ...init, headers: { "content-type": "application/json", ...(token ? { authorization: `Bearer ${token}` } : {}), ...(init.headers ?? {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof payload.error === "string" ? payload.error : "Request failed"); return payload as T; }
export const leadDiscoveryApi = { search: (input: BusinessSearchInput, token: string) => request<BusinessSearchResult>("/search", { method: "POST", body: JSON.stringify(input), token }), history: (token: string) => request<{ history: Array<{ id: string; query: string; provider: string; resultsReturned: number; newLeadsCreated: number; duplicatesDetected: number; createdAt: string }> }>("/history", { token }) };
export const authApi = { login: async (email: string, password: string, organizationId?: string) => { const authBase = baseUrl.replace(/\/lead-discovery$/, ""); const response = await fetch(`${authBase}/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, password, organizationId }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(typeof payload.error === "string" ? payload.error : "Login failed"); return payload as { token: string; user: { id: string; email: string; displayName: string | null } }; } };
export const leadApi = { list: (token: string, status?: LeadStatus) => request<{ leads: Lead[] }>(`/leads${status ? `?status=${status}` : ""}`, { token }), coverage: (token: string, missing?: string) => request<{ leadCount: number; fields: Array<{ key: string; field: string; coverage: number; missing: number }>; missingLeads: Lead[] }>(`/coverage${missing ? `?missing=${missing}` : ""}`, { token }), updateStatus: (id: string, status: LeadStatus, token: string) => request<{ ok: true }>(`/leads/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }), token }) };
export const leadPipelineApi = { summary: (token: string) => request<PipelineSummary>("/summary", { token }), pipeline: (token: string) => request<{ statuses: LeadStatus[]; columns: Record<LeadStatus, Lead[]> }>("/pipeline", { token }) };
export const collectionsApi = { list: (token: string) => request<{ collections: Array<{ id: string; name: string; leadCount: number }> }>("/collections", { token }), create: (name: string, token: string) => request<{ id: string; name: string }>("/collections", { method: "POST", body: JSON.stringify({ name }), token }), leads: (id: string, token: string) => request<{ leads: Lead[] }>(`/collections/${id}/leads`, { token }) };
export const intelligenceApi = { history: leadDiscoveryApi.history, duplicates: (token: string) => request<{ duplicates: Array<{ id: string; leadAName: string; leadBName: string; ruleName: string; confidence: number }> }>("/duplicates", { token }), resolveDuplicate: (candidateId: string, action: "keep_a" | "keep_b" | "merge" | "ignore", token: string) => request<{ ok: true }>("/duplicates/resolve", { method: "POST", body: JSON.stringify({ candidateId, action }), token }), exportPreview: (token: string) => request<{ rows: Lead[]; count: number; csvSafe: boolean }>("/export/preview", { method: "POST", body: JSON.stringify({}), token }) };
